---
- name: Reload BIND
  ansible.builtin.service:
    name: "{{ bind_service }}"
    state: reloaded

- name: Restart BIND
  ansible.builtin.service:
    name: "{{ bind_service }}"
    state: restarted
